/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chuanmei_l05usingjni_People */

#ifndef _Included_com_chuanmei_l05usingjni_People
#define _Included_com_chuanmei_l05usingjni_People
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chuanmei_l05usingjni_People
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chuanmei_l05usingjni_People_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_chuanmei_l05usingjni_People
 * Method:    getAge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_chuanmei_l05usingjni_People_getAge
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
